# Deployment for PgAdmin
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin-deployment
  labels:
    app: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
      - name: pg-admin
        image: dpage/pgadmin4:6.17
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_PASSWORD
          # value: "123456"
          valueFrom:
            secretKeyRef:
              name: pg-admin-secrets
              key: PGADMIN_PASSWORD
        - name: PGADMIN_DEFAULT_EMAIL
          # value: "superman@gmail.com"
          valueFrom:
            secretKeyRef:
              name: pg-admin-secrets
              key: PG_USER_EMAIL
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          value: "False"
        - name: PGADMIN_LISTEN_PORT
          value: "80"
---
# Service for PgAdmin
apiVersion: v1
kind: Service
metadata:
  name: pg-admin-service
spec:
  type: NodePort
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80 # Puerto que se expone hacia fuera del servicio
      targetPort: 80 # Puerto que apunta al del contenedor
      nodePort: 30000
