# Secret for PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # base64 encoded "postgres"
  DB_USER: cG9zdGdyZXM=
  # base64 encoded "t0p-Secret"
  DB_PASSWORD: dDBwLVNlY3JldA==