version: '3'


services:
  app:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile

    # Command ya se encuentra en el Dockerfile 
    #command: yarn start:dev
    image: jtejada/teslo-shop-backend:2.0.0
    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}