version: '3.1'
services:
  db:
    image: postgres:15.1
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6.17
    container_name: pgAdmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: superman@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres-db:
    external: true
  